### ISSUE TITLE
Links not work into the modal

### ISSUE THREAD

**Issue by fonfon6666** [marksmccann/modality#2]
Hello,

I try to insert a link into the modal, but not work.

Have you a solution ?

Thanks

Nico

**Comment by marksmccann** [comment]
Sorry but, could you give me some more details? I am happy to help you solve the problem, just need some more info.

**Comment by fonfon6666** [comment]
Ok, sorry but my english is bad... :-)

Check this link: http://www.g-incub.info
Open the menu (top left), and click on "Obtenir MonProfil"
And click on "Go to GOOGLE" (this link not work)

**Comment by marksmccann** [comment]
fonfon6666,

I have figured out the problem. Thank you SO much for bringing this issue to my attention. There is a problem with my 'clickOffToClose' setting. I will try and get that fixed in the next couple days and get back to you, but in the mean time, if you set 'clickOffToClose' to false, it will work for you. 

Modality.init( '#yourModalId' , { clickOffToClose: false });

Thanks Again.

**Comment by marksmccann** [comment]
That new version of Modality is up and it includes the fix to the problem you were facing. :) Download the new version and update it on your site. Everything should work for you now. Keep in mind some of the settings names have changed, refer to documentation for details.

Thanks again.

**Comment by fonfon6666** [comment]
Thanks for your help and Modality update !!!!
 Best regards

Nicolas

**Comment by marksmccann** [comment]
You are very welcome. Let me know if you have any other issues. :)
